### ISSUE TITLE
Error 404 -- Last build failed

### ISSUE THREAD

**Issue by Levak** [SeanCline/PythonSymbols#1]
Hi,

Going to http://pythonsymbols.sdcline.com/symbols returns an error 404 for me.

I see that the last build on https://travis-ci.org/SeanCline/PythonSymbols/builds/642531627 yielded a fail 3 days ago for what looks like a timeout. Can this be related?

If yes, can the build be simply relaunched to fix it? Or will it take a longer analysis to bring the symbols back online?

Or am I completely wrong in thinking that http://pythonsymbols.sdcline.com/symbols should show something instead of a 404 error?

Usecase: I wanted to download the symbols as the VM I want to debug the dump file does not have internet access.

**Comment by SeanCline** [comment]
Sorry, I didn't see this issue months ago.

It looks like the symbol repository just got too big to push in one go. I've just made [a commit](https://github.com/SeanCline/PythonSymbols/commit/1f92fdab094cbf5049946fb737d40b4c2fc8bb9b) that should take care of this by making an incremental push to the `gh-pages` branch. It also turns on the verbose flag -- hopefully the extra console output will keep TravisCI from assuming there was a stall.

Anyway, things seem to be up and running now. Hopefully it stays that way.

**Comment by sparrowt** [comment]
It's giving a 404 again, should I open a new issue?

**Comment by SeanCline** [comment]
@sparrowt Things look alright to me. That 404 is normal behaviour. I never created an `index.html` so Github doesn't know what to display.

You can see that symbols are still being updated in the [gh-pages branch](https://github.com/SeanCline/PythonSymbols/tree/gh-pages/symbols).

**Comment by sparrowt** [comment]
Ah ok apologies - windbg was failing to pull symbols after `!pysymfix` and so then when I found this ticket I wrongly assumed from the above that 404 was unexpected, sorry!

It's working today so not sure what the issue was yesterday 🤷‍♂️
